---
# Simplified ApplicationSet for Event-Driven Platform
# Uses direct YAML manifests for maximum compatibility
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eventing-platform-simple
  namespace: argocd
  labels:
    app.kubernetes.io/name: eventing-platform
    app.kubernetes.io/component: gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - list:
        elements:
          # Namespaces
          - name: namespaces
            path: infrastructure
            syncWave: "0"

          # Kafka Cluster
          - name: kafka-cluster
            path: environments/production
            file: kafka-cluster.yaml
            syncWave: "2"

          # Knative Eventing CR
          - name: knative-eventing
            path: environments/production
            file: knative-eventing-cr.yaml
            syncWave: "3"

          # Kafka Broker Config
          - name: kafka-broker-config
            path: environments/production
            file: kafka-broker-config.yaml
            syncWave: "3"

          # Kafka Broker Integration
          - name: kafka-broker
            path: environments/production
            file: kafka-broker-integration.yaml
            syncWave: "5"

          # Network Policies
          - name: network-policies
            path: environments/production
            file: network-policies.yaml
            syncWave: "6"

  template:
    metadata:
      name: 'eventing-{{.name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{.name}}'
        app.kubernetes.io/component: eventing
        app.kubernetes.io/part-of: event-driven-platform
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: eventing

      source:
        repoURL: 'https://github.com/itufan/gitops-eventing.git'
        targetRevision: main
        path: '{{.path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: eventing

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m

      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/volumeClaimTemplates
            - /spec/replicas
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

---
# Separate Application for Strimzi Operator (external URL)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventing-strimzi-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: strimzi-operator
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Replace=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eventing

  source:
    repoURL: 'https://github.com/strimzi/strimzi-kafka-operator'
    targetRevision: '0.44.0'
    path: install/cluster-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

---
# Separate Application for Knative Operator (external URL)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventing-knative-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Replace=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eventing

  source:
    repoURL: 'https://github.com/knative/operator'
    targetRevision: 'knative-v1.15.2'
    path: config

  destination:
    server: https://kubernetes.default.svc
    namespace: knative-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

---
# Separate Application for Kafka Broker Controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventing-kafka-broker-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: kafka-broker-controller
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eventing

  source:
    repoURL: 'https://github.com/knative-extensions/eventing-kafka-broker'
    targetRevision: 'knative-v1.15.0'
    path: config/source/multi

  destination:
    server: https://kubernetes.default.svc
    namespace: knative-eventing

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
