---
# ArgoCD ApplicationSet for Event-Driven Platform
# Simplified version with separate applications per component type
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eventing-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: eventing-infrastructure
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: event-driven-platform
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - list:
        elements:
          # Wave 0: Infrastructure
          - name: eventing-namespaces
            namespace: argocd
            path: infrastructure
            syncWave: "0"

          # Wave 1: Knative Operator namespace
          - name: knative-operator-ns
            namespace: knative-operator
            path: infrastructure/knative-operator
            syncWave: "1"

          # Wave 2: Kafka Cluster
          - name: kafka-cluster
            namespace: eventing
            path: environments/production
            file: kafka-cluster.yaml
            syncWave: "2"

          # Wave 3: Knative Eventing
          - name: knative-eventing-cr
            namespace: knative-eventing
            path: environments/production
            file: knative-eventing-cr.yaml
            syncWave: "3"

          - name: kafka-broker-config
            namespace: knative-eventing
            path: environments/production
            file: kafka-broker-config.yaml
            syncWave: "3"

          # Wave 5: Default Broker
          - name: default-kafka-broker
            namespace: knative-eventing
            path: environments/production
            file: kafka-broker-integration.yaml
            syncWave: "5"

          # Wave 6: Network Policies
          - name: network-policies
            namespace: eventing
            path: environments/production
            file: network-policies.yaml
            syncWave: "6"

  template:
    metadata:
      name: 'eventing-{{.name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{.name}}'
        app.kubernetes.io/component: eventing
        app.kubernetes.io/part-of: event-driven-platform
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: eventing

      source:
        repoURL: 'https://github.com/itufan/gitops-eventing.git'
        targetRevision: main
        path: '{{.path}}'
        {{- if .file }}
        directory:
          include: '{{.file}}'
        {{- end }}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m

      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/volumeClaimTemplates
            - /spec/replicas
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

---
# Separate Application for Strimzi Operator (Helm chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventing-strimzi-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: strimzi-operator
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eventing

  sources:
    - repoURL: oci://quay.io/strimzi-helm/strimzi-kafka-operator
      chart: strimzi-kafka-operator
      targetRevision: "0.48.0"
      helm:
        releaseName: strimzi-operator
        valueFiles:
          - $values/environments/production/strimzi-values.yaml
    - repoURL: 'https://github.com/itufan/gitops-eventing.git'
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

---
# Separate Application for Knative Operator (external URL)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventing-knative-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eventing

  source:
    repoURL: 'https://github.com/knative/operator'
    targetRevision: knative-v1.19.4
    path: config

  destination:
    server: https://kubernetes.default.svc
    namespace: knative-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

---
# Separate Application for Kafka Broker Controller (external URL)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventing-kafka-broker-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: kafka-broker-controller
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eventing

  source:
    repoURL: 'https://github.com/knative-extensions/eventing-kafka-broker'
    targetRevision: knative-v1.19.7
    path: config/source/multi

  destination:
    server: https://kubernetes.default.svc
    namespace: knative-eventing

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
