---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-operator
  labels:
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: event-driven-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: event-driven-platform
