---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: event-driven-platform
    networking/allow-from-knative: "true"
    networking/allow-prometheus: "true"
